const coursesS = [
    {
        id: 1,
        department_id: 101,
        teachers: [201, 202],
        classroom: 301,
        nameA: "مقدمة في البرمجة",
        nameE: "Introduction to Programming",
        code: "CS101",
        type: "Core",
        year: 2023,
        semester: 1,
        ICEF: "ICEF001",
        major: "Computer Science",
        shortcut: "CS",
        hours: 3,
        hoursT: 2,
        hoursP: 1,
        prerequsitByCode: ["CS100"],
        prerequsit: [100],
        hoursPrerequsit: 3,
        descriptionA: "هذه الدورة مقدمة في البرمجة.",
        descriptionE: "This course is an introduction to programming."
    },
    {
        id: 2,
        department_id: 102,
        teachers: [203],
        classroom: 302,
        nameA: "هندسة البرمجيات",
        nameE: "Software Engineering",
        code: "CS201",
        type: "Core",
        year: 2023,
        semester: 2,
        ICEF: "ICEF002",
        major: "Computer Science",
        shortcut: "SE",
        hours: 4,
        hoursT: 3,
        hoursP: 1,
        prerequsitByCode: ["CS101"],
        prerequsit: [1],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة مبادئ هندسة البرمجيات.",
        descriptionE: "This course covers the principles of software engineering."
    },
    {
        id: 3,
        department_id: 103,
        teachers: [204, 205],
        classroom: 303,
        nameA: "قواعد البيانات",
        nameE: "Database Systems",
        code: "CS301",
        type: "Elective",
        year: 2023,
        semester: 1,
        ICEF: "ICEF003",
        major: "Information Technology",
        shortcut: "DB",
        hours: 3,
        hoursT: 2,
        hoursP: 1,
        prerequsitByCode: ["CS201"],
        prerequsit: [2],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة أساسيات قواعد البيانات.",
        descriptionE: "This course covers the fundamentals of database systems."
    },
    {
        id: 4,
        department_id: 104,
        teachers: [206],
        classroom: 304,
        nameA: "الذكاء الاصطناعي",
        nameE: "Artificial Intelligence",
        code: "CS401",
        type: "Elective",
        year: 2023,
        semester: 2,
        ICEF: "ICEF004",
        major: "Computer Science",
        shortcut: "AI",
        hours: 3,
        hoursT: 2,
        hoursP: 1,
        prerequsitByCode: ["CS301"],
        prerequsit: [3],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة مفاهيم الذكاء الاصطناعي.",
        descriptionE: "This course covers the concepts of artificial intelligence."
    },
    {
        id: 5,
        department_id: 105,
        teachers: [207, 208],
        classroom: 305,
        nameA: "تطوير الويب",
        nameE: "Web Development",
        code: "CS501",
        type: "Core",
        year: 2023,
        semester: 1,
        ICEF: "ICEF005",
        major: "Information Technology",
        shortcut: "WD",
        hours: 4,
        hoursT: 3,
        hoursP: 1,
        prerequsitByCode: ["CS101"],
        prerequsit: [1],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة تطوير تطبيقات الويب.",
        descriptionE: "This course covers web application development."
    },
    {
        id: 6,
        department_id: 106,
        teachers: [209],
        classroom: 306,
        nameA: "تحليل البيانات",
        nameE: "Data Analysis",
        code: "CS601",
        type: "Elective",
        year: 2023,
        semester: 2,
        ICEF: "ICEF006",
        major: "Data Science",
        shortcut: "DA",
        hours: 3,
        hoursT: 2,
        hoursP: 1,
        prerequsitByCode: ["CS201"],
        prerequsit: [2],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة تقنيات تحليل البيانات.",
        descriptionE: "This course covers data analysis techniques."
    },
    {
        id: 7,
        department_id: 107,
        teachers: [210, 211],
        classroom: 307,
        nameA: "أمن المعلومات",
        nameE: "Information Security",
        code: "CS701",
        type: "Core",
        year: 2023,
        semester: 1,
        ICEF: "ICEF007",
        major: "Cybersecurity",
        shortcut: "IS",
        hours: 3,
        hoursT: 2,
        hoursP: 1,
        prerequsitByCode: ["CS101"],
        prerequsit: [1],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة أساسيات أمن المعلومات.",
        descriptionE: "This course covers the fundamentals of information security."
    },
    {
        id: 8,
        department_id: 108,
        teachers: [212],
        classroom: 308,
        nameA: "تطبيقات الهواتف الذكية",
        nameE: "Mobile Applications",
        code: "CS801",
        type: "Elective",
        year: 2023,
        semester: 2,
        ICEF: "ICEF008",
        major: "Computer Science",
        shortcut: "MA",
        hours: 3,
        hoursT: 2,
        hoursP: 1,
        prerequsitByCode: ["CS501"],
        prerequsit: [5],
        hoursPrerequsit: 3,
        descriptionA: "تتناول هذه الدورة تطوير تطبيقات الهواتف الذكية.",
        descriptionE: "This course covers mobile application development."
    }
];


export {coursesS}